# Generated by Django 5.2.9 on 2025-12-05 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "model_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("workspace", models.CharField(max_length=255)),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("lightgbm", "LightGBM"),
                            ("xgboost", "XGBoost"),
                            ("random_forest", "Random_Forest"),
                            ("gradient_boosting", "Gradient_Boosting_Machine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("parameter", models.JSONField(blank=True, null=True)),
                ("tuning", models.CharField(max_length=50)),
                ("dependent_var", models.TextField()),
                ("excluded_var", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("metrics", models.JSONField(blank=True, null=True)),
                ("feature", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model_id",
                    models.ForeignKey(
                        db_column="model_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.model",
                    ),
                ),
            ],
            options={
                "db_table": "session",
            },
        ),
        migrations.CreateModel(
            name="UserSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_sequence_id",
                    models.IntegerField(db_column="user_sequence_id", default=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_id",
                    models.ForeignKey(
                        db_column="model_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.model",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_seq",
                "unique_together": {("user_id", "user_sequence_id")},
            },
        ),
    ]
