# Generated by Django 5.2.9 on 2025-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("training", "Training"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=50,
            ),
        ),
    ]
