# Generated by Django 5.2.9 on 2025-12-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_alter_session_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="excluded_var",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
