# Generated by Django 5.2.9 on 2025-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_alter_model_excluded_var"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("lightgbm", "Lightgbm"),
                    ("xgboost", "Xgboost"),
                    ("random_forest", "Random Forest"),
                    ("gradient_boosting", "Gradient Boosting"),
                ],
                max_length=50,
            ),
        ),
    ]
