# Generated by Django 6.0 on 2026-01-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_alter_model_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='top_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
